# Tomcat
server:
  port: 8089


spring:
  application:
    name: s686mall-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_ums
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.s686.mall.s686mallmaster.entity
